
var __cov_HqyuNSi2KJVJKeLThbm2mw = (Function('return this'))();
if (!__cov_HqyuNSi2KJVJKeLThbm2mw.__coverage__) { __cov_HqyuNSi2KJVJKeLThbm2mw.__coverage__ = {}; }
__cov_HqyuNSi2KJVJKeLThbm2mw = __cov_HqyuNSi2KJVJKeLThbm2mw.__coverage__;
if (!(__cov_HqyuNSi2KJVJKeLThbm2mw['D:\\data\\git_projects\\f1feeder-part1\\app\\js\\services.js'])) {
   __cov_HqyuNSi2KJVJKeLThbm2mw['D:\\data\\git_projects\\f1feeder-part1\\app\\js\\services.js'] = {"path":"D:\\data\\git_projects\\f1feeder-part1\\app\\js\\services.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"b":{},"f":{"1":0,"2":0,"3":0,"4":0},"fnMap":{"1":{"name":"(anonymous_1)","line":2,"loc":{"start":{"line":2,"column":31},"end":{"line":2,"column":47}}},"2":{"name":"(anonymous_2)","line":6,"loc":{"start":{"line":6,"column":27},"end":{"line":6,"column":38}}},"3":{"name":"(anonymous_3)","line":13,"loc":{"start":{"line":13,"column":33},"end":{"line":13,"column":46}}},"4":{"name":"(anonymous_4)","line":20,"loc":{"start":{"line":20,"column":31},"end":{"line":20,"column":44}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":28,"column":5}},"2":{"start":{"line":4,"column":4},"end":{"line":4,"column":23}},"3":{"start":{"line":6,"column":4},"end":{"line":11,"column":5}},"4":{"start":{"line":7,"column":6},"end":{"line":10,"column":9}},"5":{"start":{"line":13,"column":4},"end":{"line":18,"column":5}},"6":{"start":{"line":14,"column":6},"end":{"line":17,"column":9}},"7":{"start":{"line":20,"column":4},"end":{"line":25,"column":5}},"8":{"start":{"line":21,"column":6},"end":{"line":24,"column":9}},"9":{"start":{"line":27,"column":4},"end":{"line":27,"column":21}}},"branchMap":{}};
}
__cov_HqyuNSi2KJVJKeLThbm2mw = __cov_HqyuNSi2KJVJKeLThbm2mw['D:\\data\\git_projects\\f1feeder-part1\\app\\js\\services.js'];
__cov_HqyuNSi2KJVJKeLThbm2mw.s['1']++;angular.module('F1FeederApp.services',[]).factory('ergastAPIservice',function($http){__cov_HqyuNSi2KJVJKeLThbm2mw.f['1']++;__cov_HqyuNSi2KJVJKeLThbm2mw.s['2']++;var ergastAPI={};__cov_HqyuNSi2KJVJKeLThbm2mw.s['3']++;ergastAPI.getDrivers=function(){__cov_HqyuNSi2KJVJKeLThbm2mw.f['2']++;__cov_HqyuNSi2KJVJKeLThbm2mw.s['4']++;return $http({method:'JSONP',url:'http://ergast.com/api/f1/2013/driverStandings.json?callback=JSON_CALLBACK'});};__cov_HqyuNSi2KJVJKeLThbm2mw.s['5']++;ergastAPI.getDriverDetails=function(id){__cov_HqyuNSi2KJVJKeLThbm2mw.f['3']++;__cov_HqyuNSi2KJVJKeLThbm2mw.s['6']++;return $http({method:'JSONP',url:'http://ergast.com/api/f1/2013/drivers/'+id+'/driverStandings.json?callback=JSON_CALLBACK'});};__cov_HqyuNSi2KJVJKeLThbm2mw.s['7']++;ergastAPI.getDriverRaces=function(id){__cov_HqyuNSi2KJVJKeLThbm2mw.f['4']++;__cov_HqyuNSi2KJVJKeLThbm2mw.s['8']++;return $http({method:'JSONP',url:'http://ergast.com/api/f1/2013/drivers/'+id+'/results.json?callback=JSON_CALLBACK'});};__cov_HqyuNSi2KJVJKeLThbm2mw.s['9']++;return ergastAPI;});
